"""clean student schema

Revision ID: 5e6a8cab0271
Revises: f84c18b95d35
Create Date: 2025-12-22 00:35:07.427869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6a8cab0271'
down_revision = 'f84c18b95d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('department_code', sa.String(length=10), nullable=True),
    sa.Column('pcode', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('year_of_joining', sa.Integer(), nullable=True),
    sa.Column('tenth_cgpa', sa.Float(), nullable=True),
    sa.Column('intermediate_cgpa', sa.Float(), nullable=True),
    sa.Column('student_mobile', sa.String(length=10), nullable=True),
    sa.Column('student_email', sa.String(length=100), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('parent_mobile', sa.String(length=10), nullable=True),
    sa.Column('parent_email', sa.String(length=100), nullable=True),
    sa.Column('admission_status', sa.String(length=20), nullable=True),
    sa.Column('residence_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_no')
    )
    op.create_table('parent_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('iat1_marks', sa.Integer(), nullable=False),
    sa.Column('iat2_marks', sa.Integer(), nullable=False),
    sa.Column('attendance_marks', sa.Integer(), nullable=False),
    sa.Column('assignment_marks', sa.Integer(), nullable=False),
    sa.Column('sem_end_marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester_marks')
    op.drop_table('parent_meeting')
    op.drop_table('student')
    # ### end Alembic commands ###
