"""add full student fields

Revision ID: f84c18b95d35
Revises: 
Create Date: 2025-12-22 00:22:18.833504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84c18b95d35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('department_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pcode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenth_cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intermediate_cgpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('student_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('permanent_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admission_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('residence_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('year_of_joining',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_mobile',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('father_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('mother_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('parent_mobile',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_column('address')
        batch_op.drop_column('department')
        batch_op.drop_column('aadhaar_no')
        batch_op.drop_column('email')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aadhaar_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('parent_mobile',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('mother_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('father_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('student_mobile',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('year_of_joining',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('residence_type')
        batch_op.drop_column('admission_status')
        batch_op.drop_column('parent_email')
        batch_op.drop_column('permanent_address')
        batch_op.drop_column('current_address')
        batch_op.drop_column('student_email')
        batch_op.drop_column('intermediate_cgpa')
        batch_op.drop_column('tenth_cgpa')
        batch_op.drop_column('year')
        batch_op.drop_column('pcode')
        batch_op.drop_column('department_code')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
